version: '3.8'

services:
  web:
    image: joe-hasson-personal-site:latest
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      - APP_ENV=local
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_healthy

  migrations:
    image: joe-hasson-personal-site-migrations:latest
    environment:
      - DATABASE_URL=${CONTAINERISED_DATABASE_URL}
    depends_on:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: >         
        /bin/sh -c 'pg_isready -U ${DB_USER} &&
        psql -U ${DB_USER} -d ${DB_NAME} -c "SELECT 1"'
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
