services:
  web:
    # We use pre-built images, here and under the migrations service,
    # rather than building from a Dockerfile, so that image builds 
    # can run as separate, parallel steps in our deployment pipeline, 
    # prior to running "docker compose up" on the server.
    image: joe-hasson-personal-site:latest
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_BASE_URL=${APP_BASE_URL}
      - APP_HMAC_SECRET=${APP_HMAC_SECRET}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - BLOG_EMAIL_ADDRESS=${BLOG_EMAIL_ADDRESS}
      - BLOG_EMAIL_PASSWORD=${BLOG_EMAIL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  migrations:
    image: joe-hasson-personal-site-migrations:latest
    environment:
      - DATABASE_URL=${CONTAINERISED_DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: >         
        /bin/sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME} &&
        psql -U ${DB_USER} -d ${DB_NAME} -c "SELECT 1"'
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: ec2-user_postgres_data
