[project]
name = "frontend4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.5",
    "jinja2>=3.1.4",
    "uvicorn>=0.32.0",
]
