[package]
name = "dynamic_site"
version = "0.1.0"
edition = "2021"

[[bin]] # double square brackets is toml array syntax: can have multiple binary crates
path = "src/main.rs"
name = "dynamic-site"

[dependencies]
actix-web = "4"
