# .github/workflows/deploy.yml
name: Test and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
        
      - name: Terraform Plan
        working-directory: ./terraform
        run: >
          terraform plan
          -var="ssh_public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"
          -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"
          -var="cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}"

      - name: Terraform Apply
        working-directory: ./terraform
        if: github.ref == 'refs/heads/main'
        run: >
          terraform apply -auto-approve
          -var="ssh_public_key=${{ secrets.EC2_SSH_PUBLIC_KEY }}"
          -var="cloudflare_api_token=${{ secrets.CLOUDFLARE_API_TOKEN }}"
          -var="cloudflare_zone_id=${{ secrets.CLOUDFLARE_ZONE_ID }}"
        
      # Store IP for use in later step
      - name: Get EC2 IP
        working-directory: ./terraform
        run: |
          echo "EC2_IP=$(terraform output -json | jq -r '.public_ip.value')" >> $GITHUB_ENV

      - name: Install nginx on server
        uses: appleboy/ssh-action@v1.0.0
        env:
          REPO: ${{ github.repository }}
        with:
          username: ec2-user
          host: ${{ env.EC2_IP }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: REPO
          script: |
            set -e
            # install nginx
            sudo yum update -y
            sudo amazon-linux-extras install nginx1 -y

      - name: Prepare server for scp
        uses: appleboy/ssh-action@v1.0.0
        with:
          username: ec2-user
          host: ${{ env.EC2_IP }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Remove default nginx config
            sudo rm -f /etc/nginx/nginx.conf
            # Remove temp files generated by subsequent steps in case they
            # weren't deleted successfully in previous runs
            sudo rm -f /tmp/nginx.conf
            sudo rm -rf /tmp/static

      - name: Push new nginx.conf to server in temp dir
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ec2-user
          host: ${{ env.EC2_IP }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "nginx.conf"
          target: "/tmp"

      - name: Render static content
        run: |
          pip install webassets jinja2
          python3 scripts/render.py

      - name: Push static content to server in temp dir
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ec2-user
          host: ${{ env.EC2_IP }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "static_site/build/*"
          target: "/tmp"

      - name: Move temp SCPed files to correct location and set permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            sudo mv /tmp/nginx.conf /etc/nginx/nginx.conf
            sudo rm -rf /static
            sudo mv /tmp/build /static
            sudo chown root:root /etc/nginx/nginx.conf
            sudo chmod 644 /etc/nginx/nginx.conf

      - name: run nginx on server
        uses: appleboy/ssh-action@v1.0.0
        env:
          REPO: ${{ github.repository }}
        with:
          username: ec2-user
          host: ${{ env.EC2_IP }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          envs: REPO
          script: |
            set -e
            # Check nginx configuration and then start
            sudo nginx -t
            sudo systemctl restart nginx
            sudo systemctl enable nginx

      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything": true}'

